# Submit all project dependencies via GitHub Dependency Submission API.
# Used by GitHub to generate Dependabot Alerts for vulnerable dependencies.
name: Dependency submission
on:
  push:
    branches: [ 'master' ]
permissions:
  contents: write
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v5
